<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'HumusStreamResponseSender\StreamResponseSenderFactory'        => __DIR__ . '/src/HumusStreamResponseSender/StreamResponseSenderFactory.php',
    'HumusStreamResponseSender\StreamResponseSender'               => __DIR__ . '/src/HumusStreamResponseSender/StreamResponseSender.php',
    'HumusStreamResponseSender\Module'                             => __DIR__ . '/src/HumusStreamResponseSender/Module.php',
    'HumusStreamResponseSender\Controller\Plugin\Stream'           => __DIR__ . '/src/HumusStreamResponseSender/Controller/Plugin/Stream.php',
    'HumusStreamResponseSender\Options'                            => __DIR__ . '/src/HumusStreamResponseSender/Options.php',
    'HumusStreamResponseSender\Exception\ExceptionInterface'       => __DIR__ . '/src/HumusStreamResponseSender/Exception/ExceptionInterface.php',
    'HumusStreamResponseSender\Exception\InvalidArgumentException' => __DIR__ . '/src/HumusStreamResponseSender/Exception/InvalidArgumentException.php',
);
